version: '3.1'

services: 
    db:
        image: mysql:5.6
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080

    backend:
        build:
            context: ./backend
        ports:
            - 3000:3000
        depends_on:
            - db
        volumes:
            - "./frontend/dist:/var/www"
        environment:
            DB_HOSTNAME: db
            STATIC_ROOT: /var/www

